version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: towa_db
    restart: always
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: towaERP
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - towa-network

  backend:
    build: ./backend
    container_name: towa_backend
    restart: always
    # Mở port 3000 để bạn vẫn có thể test trực tiếp nếu cần
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      # SỬA TẠI ĐÂY: Dùng 'db' thay vì IP nội bộ để Docker tự kết nối
      DATABASE_URL: "postgresql://myadmin:P@ssw0rd@db:5432/towaERP?schema=public"
      # FRONTEND_URL sẽ được lấy từ file .env backend
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - towa-network

  frontend:
    build: ./fontend
    container_name: towa_fontend
    restart: always
    ports:
      - "90:90"
    depends_on:
      - backend
    networks:
      - towa-network

volumes:
  postgres_data:

networks:
  towa-network:
    driver: bridge