version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: towa_db
    restart: always
    environment:
      POSTGRES_USER: myadmin          # Tên user
      POSTGRES_PASSWORD: P@ssw0rd      # Mật khẩu
      POSTGRES_DB: towaERP
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - towa-network

  backend:
    build: ./backend
    container_name: towa_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      # Sử dụng thông tin khớp hoàn toàn với service 'db' ở trên
      DATABASE_URL: "postgresql://myadmin:P@ssw0rd@db:5432/towaERP?schema=public"
    # THÊM ĐOẠN NÀY NẾU CHƯA CÓ
    
    depends_on:
      - db
    networks:
      - towa-network

  frontend:
    build: ./fontend
    container_name: towa_fontend
    restart: always
    ports:
      - "90:90"
    depends_on:
      - backend
    networks:
      - towa-network

volumes:
  postgres_data:

networks:
  towa-network:
    driver: bridge